### PR TITLE
Assign experimental status to some templates

### PR DESCRIPTION
**Pull request by sovrasov**
cc @kprokofi

### CODE REVIEW

**Review by kprokofi — COMMENTED** [review]
I thought we should rename the `mobilenet_v3_large_75` to the experimental template since it is not used in SC MVP, not the `large_1`, shouldn't we?

**Comment by sovrasov** [comment]
I convinced Sergey that we should leave `mobilenet_v3_large_75`

**Comment by kprokofi** [comment]
But it doesn't have imagenet21k weights for multilabel purposes and the quality gap between mobilenetv3_large_1 and *_75 is palpable on this task

**Comment by kprokofi** [comment]
On the other hand, we still can have time to train it on OI before the release

**Comment by kprokofi** [comment]
And EfficientNetB0 either doesn't have imagenet21k weights though

**Pull request merged**
