### PR TITLE
[NNCF] Requirements

### PR DESCRIPTION
**Pull request by alexsu52**
Added NNCF to requirements.txt

### CODE REVIEW

**Comment by nervana-ff** [comment]
Can one of the admins verify this patch?

**Comment by sovrasov** [comment]
@alexsu52 could you please review the pylint error?
```
************* Module torchreid.integration.nncf.compression
torchreid/integration/nncf/compression.py:240:[8](https://github.com/openvinotoolkit/deep-object-reid/runs/5431751404?check_suite_focus=true#step:7:8): E1137: 'nncf_metainfo' does not support item assignment (unsupported-assignment-operation)
```
Is it relevant?

**Comment by alexsu52** [comment]
> @alexsu52 could you please review the pylint error?
> 
> ```
> ************* Module torchreid.integration.nncf.compression
> torchreid/integration/nncf/compression.py:240:[8](https://github.com/openvinotoolkit/deep-object-reid/runs/5431751404?check_suite_focus=true#step:7:8): E1137: 'nncf_metainfo' does not support item assignment (unsupported-assignment-operation)
> ```
> 
> Is it relevant?

done

**Comment by sovrasov** [comment]
@alexsu52 is it ready for merge?

**Pull request merged**
